spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/agenda_contatos
    username: postgres
    password: admin

  sql:
    init:
      mode: always
      
server.servlet.context-path=/agenda_contatos
